### ISSUE TITLE
Remove master and add v2.x.x

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/makd#20]
As per our SemVer guidelines, the `master` branch should be removed, and a `v2.x.x` should be provided for future breaking changes.

**Comment by leandro-lucarella-sociomantic** [comment]
Also the default branch v1.4.x is wrong, it should be v1.x.x.

**Comment by leandro-lucarella-sociomantic** [comment]
I'm not sure if it makes sense to create a v2.x.x branch makes sense though, v2.x.x should be branched off when breaking changes are introduced, otherwise it just adds maintenance burden.

Once a PR is created for the v2.0.0 milestone (breaking changes), we can create the branch and change the base branch of the PR.

**Comment by leandro-lucarella-sociomantic** [comment]
All updated now, I also removed the v1.4.x branch as it is 3 months old already.

**Comment by mathias-lang-sociomantic** [comment]
I asked for v2.x.x because I had a breaking change in mind :dancers:

**Comment by leandro-lucarella-sociomantic** [comment]
Fire away! Just do it against v1.x.x and say is a breaking change that should go to v2.0.0.
