### ISSUE TITLE
Auto-generated package dependencies don't consider versions

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/makd#32]
When deb packages are generated by makd, dependencies are automatically generated.  However, these dependencies do not take versions into account, meaning that a package might successfully install on a machine with an older, incompatible library version.

**Comment by llucax** [comment]
I'm tempted to close this as won't fix. MakD can't guess what are the exact version dependencies for your binaries. Just because you have a library version X installed, it doesn't mean it couldn't build with other versions, so just putting the current version would be too strict.

If you need that level of control for dependencies, you need to specify dependencies manually.

I actually will close this as won't fix, but feel free to re-open if you think it was misinterpreted or something! :)

**Comment by joseph-wakeling-sociomantic** [comment]
Sure, no problem.  I wonder though if there's a way to specify dependency version constraints in `Build.mak` or `Config.mak` such that `make pkg` could pick them up?

Seems like it would be less likely to get out of sync with actual dependencies this way.

**Comment by leandro-lucarella-sociomantic** [comment]
What do you mean? You can specify them in the `.pkg` file.

**Comment by joseph-wakeling-sociomantic** [comment]
OK, fair enough.
