### ISSUE TITLE
`make pkg` cannot handle UTF8 in author/committer names

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/makd#33]
This is the same problem as sociomantic/makd#30, but occurs in `get_git_author` instead:
https://github.com/sociomantic-tsunami/makd/blob/v1.x.x/git-deblog#L54-L65

Turns out unicode characters are a bit more widely spread in git history than just the commit messages ;-)

**Comment by leandro-lucarella-sociomantic** [comment]
Even when that could be another source of trouble, the problem is in `ti = run('git cat-file tag'.split() + [t], stderr=PIPE)`. But this really tricky, because we can't really assume much about the encoding. It's very common for it to be UTF-8 but I think git doesn't enforce it in any way, so users could use another one.

By using [locale.getdefaultlocale()](https://docs.python.org/3/library/locale.html#locale.getdefaultlocale) we just trust the user configuration (`LANG` and other related env variables), but for some reason that seems to be failing sometimes.

**Comment by leandro-lucarella-sociomantic** [comment]
Everything seems to be working correctly, the problem reported here seemed to come from a misconfiguration.

Still, exploding in the user's face when a encoding problem is found is not cool, and a PR to fix that is coming up.
